# Use the official Node.js image as the base image
FROM node:23.4.0-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and tsconfig.json to the working directory
COPY package.json tsconfig.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Install Graphviz
# Install Graphviz
RUN apk update && apk add graphviz

# Copy the backend folder to the working directory
COPY . .

# Build the TypeScript code
RUN npx tsc -p tsconfig.json

# Expose port
EXPOSE 3000

# Set default command
CMD ["node", "dist/index.js"]