
# Stage 1: Build the Angular application
# Use an official Node.js runtime as a parent image
FROM node:23.4.0 as build

# Set the working directory in the container
WORKDIR /frontend/codevisor

# Copy the package*.json files
COPY package*.json ./

# Install the dependencies
RUN npm install

# Install the Angular CLI
RUN npm install -g @angular/cli
# Copy the application code
COPY . .

RUN ng build

# Stage 2: Serve the Angular application using Nginx
FROM nginx:1.27.3

RUN rm /etc/nginx/conf.d/default.conf
# Remove all files in the default Nginx HTML folder
RUN rm -rf /usr/share/nginx/html/*

COPY --from=build /frontend/codevisor/dist/* /usr/share/nginx/html/

RUN mv /usr/share/nginx/html/browser/* /usr/share/nginx/html/ && \
    rm -rf /usr/share/nginx/html/browser
    
COPY nginx.conf /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]