# Use an official Node.js runtime as a parent image
FROM node:22

# Set the working directory in the container
WORKDIR /app

# Copy the package*.json files
COPY package*.json ./

# Install the dependencies
RUN npm install

# Install the Angular CLI
RUN npm install -g @angular/cli
# Copy the application code
COPY . .

# Expose the port
EXPOSE 4200

# Run the command to start the development server
CMD ["ng", "serve", "--host", "0.0.0.0"]